name: .NET Core

on: [push]

jobs:
  build_and_test:

    runs-on: windows-latest

    steps:
    - name: Setup .NET Core if needed
      uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: 3.0.100
    - uses: actions/checkout@v1
    - name: Build with dotnet
      run: dotnet build -c Release
    - name: Test with dotnet
      run: dotnet test -c Release      
